version: build-{build}.{branch}
clone_depth: 3

platform: x64
image: Visual Studio 2019

before_build:
  - set "JAVA_HOME=C:\Program Files\Java\jdk17"
  - set "PATH=C:\Program Files\Java\jdk17\bin;%PATH%"

build_script:
  - bld.bat download compile

test_script:
  - bld.bat test

cache:
  - C:\Users\appveyor\.m2
